# Generated by Django 5.1.3 on 2024-12-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=256)),
                ('muallifi', models.CharField(max_length=256)),
                ('yili', models.DateField(auto_now_add=True)),
                ('betlari_soni', models.IntegerField()),
                ('janri', models.CharField(max_length=256)),
                ('rasmi', models.ImageField(upload_to='rasmlar/')),
                ('malumot', models.TextField()),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='Vazifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=256)),
                ('izoh', models.TextField()),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifa',
            },
        ),
    ]
